name: Label New Issues

on:
  issues:
    types:
      - opened

jobs:
  label-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Add "To Do" label to new issue
        uses: actions/labeler@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'To Do'
